### ISSUE TITLE
Sample code provided in the request response with RabbitMQ page does not work properly

### ISSUE THREAD

**Issue by ShammiL** [wso2/docs-mi#675]
## Description
In the scenario on the [documentation](https://mi.docs.wso2.com/en/latest/learn/examples/rabbitmq-examples/request-response-rabbitmq/) page, the `OrderProcessingService` calls a backend that returns a response that the proxy service adds to a RabbitMQ queue. No instructions are provided on how to set up the backend being called before the changes are done in #548.
The new changes instruct the user on how to set up a new backend which can be called by the order processing proxy service. But when the request is sent, it gives the following error.
> ERROR {RelayUtils} - Error while building Passthrough stream org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566)
	at org.apache.axis2.builder.ApplicationXMLBuilder.processDocument(ApplicationXMLBuilder.java:94)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:153)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:178)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:131)
	at org.apache.synapse.transport.util.PassThroughMessageHandler.buildMessage(PassThroughMessageHandler.java:103)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.buildMessage(Axis2SynapseEnvironment.java:913)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:593)
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:430)
	at org.apache.synapse.endpoints.AddressEndpoint.send(AddressEndpoint.java:79)
	at org.apache.synapse.mediators.builtin.CallMediator.handleNonBlockingCall(CallMediator.java:387)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:200)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:126)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:74)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:240)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:401)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:460)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:208)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
@ShammiL What is the URL of the page where this issue is?

**Comment by ShammiL** [comment]
URL for the documentation: https://mi.docs.wso2.com/en/latest/learn/examples/rabbitmq-examples/request-response-rabbitmq/
Updated the description as well

**Comment by GDLMadushanka** [comment]
This issue can be resolved by changing the log level in OrderProcessingService proxy.
But this is not the proper fix, and we need to debug and check why the message is not getting built correctly.

**Comment by GDLMadushanka** [comment]
Fixed in https://github.com/wso2/docs-mi/pull/1102 
Added an issue in MI to fix the runtime issue https://github.com/wso2/product-micro-integrator/issues/3778
